### ISSUE TITLE
PolyMC Portable doesn't keep configs

### ISSUE THREAD

**Issue by otavio-silva** [404NetworkError/scoop-bucket#1]
## Bug Report

**polymc-portable:** [name of package which has bug(s)]

### Current Behaviour

Every time I open the app, it pops the configuration step-by-step on choosing the Java JRE, memory allocation, language and it also requires that I log in with my Microsoft account. If I close the software and open it, it will ask for all those information again as if I never opened it before. It keeps Minecraft instances I created though.

### Expected Behaviour

I imagine once I configured the program, it would save all that info so I don't have to do it all over again.

### Additional context/output

I added the bucket through `scoop bucket add 404NetworkError https://github.com/404NetworkError/scoop-bucket` and used `scoop install polymc-portable -g` to install it.

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by 404NetworkError** [comment]
This is not an issue with my Scoop bucket specifically. It's a problem with PolyMC and how it interacts with the `polymc.cfg`. See my [issue](https://github.com/PolyMC/PolyMC/issues/1169) on their repo.

As a workaround, you will have to manually copy the `polymc.cfg` from any existing installs to the newest (or `current`) version.
