### ISSUE TITLE
[CRITICAL]: freeze PolyMC updates as the maintainer's account has been compromised

### ISSUE THREAD

**Issue by otavio-silva** [404NetworkError/scoop-bucket#2]
## Bug Report

**Package Name:** `polymc-portable`

### Additional context/output

The current PolyMC status is heavily compromised, see https://github.com/Calinou/scoop-games/issues/720

### Possible Solution

Freeze package updates or remove it

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "last_update": "2022-10-17T17:25:21.8439909-03:00",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}
```

**Comment by 404NetworkError** [comment]
Deleted following the direction of Calinou. Leaving this issue open until the program can be restored.

**Comment by 404NetworkError** [comment]
Added PrismLauncher. See commit bbcf97e.
