### ISSUE TITLE
usbtreeview@3.8.6: hash check failed

### ISSUE THREAD

**Issue by successtheman** [404NetworkError/scoop-bucket#7]
Updating 'usbtreeview' (3.8.5 -> 3.8.6)
Downloading new version
UsbTreeView_x64.zip (387.2 KB) [==============================================================================] 100%
Checking hash of UsbTreeView_x64.zip ... ERROR Hash check failed!
App:         404NetworkError/usbtreeview
URL:         https://www.uwe-sieber.de/files/UsbTreeView_x64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    757b5038b622d18d138d2a537a534e546050704401d9f7ffa2d5c84c68681966
Actual:      598fc376af073a3da39c590359120ea1cd5278d818346d48956d55654e33caf9

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/404NetworkError/scoop-bucket/issues/new?title=usbtreeview%403.8.6%3a+hash+check+failed

**Comment by successtheman** [comment]
The ease of reporting is really what made me want to do it, just copying and pasting it can't get any simpler, so I appreciate the simplification of the work flow for reporting such issues

**Comment by 404NetworkError** [comment]
Honestly, the praise should really go to the devs over at [ScoopInstaller/BucketTemplate](https://github.com/ScoopInstaller/BucketTemplate) for setting up a great template that handles all of the GitHub Actions (including updating buckets). Feel free to create your own bucket that is more specialized to your needs using this template if you like.
